version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly 
    groups:
      python-build-tools:
        patterns:
          - "pip"
          - "setuptools"
          - "wheel"
          - "poetry"
      python-dev-tools:
        patterns:
          - "pytest*"
          - "coverage"
          - "flake8"
          - "mypy*"
          - "black"
          - "autoflake"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      javascript-build-tools:
        patterns:
          - "yarn"
          - "npm"
          - "babel*"
      javascript-dev-tools:
        patterns:
          - "prettier"
          - "@testing-library/*"
          - "react-scripts"
          - "foreman"