from django.db import models


class Device(models.Model):
    """
    Stores a single device registration. This entry is created when the app
    is installed and a registration call is made from the device.
    This is always linked to a user's account - :model: `home.Account`.
    All the daily and intentional walks link back to this
    """

    device_id = models.CharField(
        max_length=250,
        primary_key=True,
        help_text=(
            "A unique id generated by the app when it is first installed"
            " on a device. Used for authentication on subsequent calls"
        ),
    )
    account = models.ForeignKey(
        "Account",
        on_delete=models.CASCADE,
        help_text="User account associated with this registered device",
    )
    created = models.DateTimeField(
        auto_now_add=True,
        help_text="When the record was created/device was registered",
    )

    def __str__(self):
        return f"{self.device_id} | {self.account} "

    class Meta:
        ordering = ("-created",)
