# Generated by Django 3.0.3 on 2020-04-05 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "account_id",
                    models.CharField(
                        max_length=250, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("zip", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="IntentionalWalk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=250)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("steps", models.IntegerField()),
                ("pause_time", models.FloatField()),
                ("distance", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "appuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.AppUser",
                    ),
                ),
            ],
            options={
                "ordering": ("-start",),
            },
        ),
        migrations.CreateModel(
            name="DailyWalk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("steps", models.IntegerField()),
                ("distance", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "appuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.AppUser",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.AddConstraint(
            model_name="dailywalk",
            constraint=models.UniqueConstraint(
                fields=("appuser", "date"), name="appuser_date"
            ),
        ),
    ]
