# Generated by Django 3.0.5 on 2020-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailywalk",
            name="event_id",
        ),
    ]
