# Generated by Django 3.0.5 on 2020-04-30 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='start_promo',
            field=models.DateField(default=datetime.date(2020, 4, 30)),
            preserve_default=False,
        ),
    ]
