# Generated by Django 3.2.9 on 2021-12-28 02:13

from django.db import migrations, models
import home.models.account
import setfield


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_new_demographic_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender_other',
            field=models.CharField(blank=True, help_text="Free-form text field for 'gender' value 'OT'", max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='race_other',
            field=models.CharField(blank=True, help_text="Free-form text field for 'race' value 'OT'", max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, help_text='Self-identified gender identity of user', max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='race',
        ),
        migrations.AddField(
            model_name='account',
            name='race',
            field=setfield.SetField(base_field=models.CharField(choices=[('NA', home.models.account.RaceLabels['NA']), ('BL', home.models.account.RaceLabels['BL']), ('AS', home.models.account.RaceLabels['AS']), ('PI', home.models.account.RaceLabels['PI']), ('WH', home.models.account.RaceLabels['WH']), ('OT', home.models.account.RaceLabels['OT'])], max_length=2), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dailywalk',
            name='date',
            field=models.DateField(help_text='The specific date for which the steps are recorded'),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
