# Generated by Django 3.2.9 on 2022-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_gender_race_fields_setfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='start_baseline',
            field=models.DateField(blank=True, help_text='Start of baseline period (prior to contest start)', null=True),
        ),
        migrations.AddField(
            model_name='dailywalk',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='True if part of contest baseline period (default: False)'),
        ),
    ]
