# Generated by Django 3.2.12 on 2022-03-21 11:07

from django.db import migrations, models

import home.models.account


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_contest_start_baseline_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="sexual_orien",
            field=models.CharField(
                blank=True,
                help_text="Self-identified sexual orientation of user",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="sexual_orien_other",
            field=models.CharField(
                blank=True,
                help_text="Free-form text field for 'sexual_orien' value 'OT'",
                max_length=75,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_latino",
            field=models.CharField(
                blank=True,
                help_text="Latino or Hispanic origin",
                max_length=2,
                null=True,
            ),
        ),
    ]
