# Generated by Django 3.2.15 on 2023-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_auto_20220321_0407"),
    ]

    operations = [
        migrations.AddField(
            model_name="intentionalwalk",
            name="walk_time",
            field=models.FloatField(
                default=0,
                help_text="Total time walked not including pause time",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            'UPDATE home_intentionalwalk SET walk_time=EXTRACT(EPOCH FROM ("end" - "start")) - pause_time'
        ),
    ]
