# Generated by Django 3.2.15 on 2023-03-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_intentionalwalk_walk_time"),
        ("home", "0011_leaderboard"),
    ]

    operations = []
