# Generated by Django 5.2.1 on 2025-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_weeklygoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="race_json",
            field=models.JSONField(default=dict),
        ),
    ]
