# Generated by Django 4.2.11 on 2024-07-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_weeklygoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_model",
            field=models.CharField(
                blank=True,
                help_text='Unique identifier for the device\'s model.\n            getDeviceid() - Gets the device ID.\n                iOS: "iPhone7,2"\n                Android: "goldfish"\n                Windows: "Y3R94UC#AC4"\n        ',
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                help_text='Manufacturer of the device.\n            getManufacturer() - Gets the device manufacturer\n                iOS: "Apple"\n                Android: "Google"\n                Windows: ?\n        ',
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="os_name",
            field=models.CharField(
                blank=True,
                help_text='Operating system of the device.\n            getSystemName() - Gets the device OS name.\n                iOS: "iOS" on newer iOS devices "iPhone OS" on older devices (including older iPad models), "iPadOS" for iPads using iPadOS 15.0 or higher.\n                Android: "Android"\n                Windows: ?\n        ',
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="os_version",
            field=models.CharField(
                blank=True,
                help_text='Device operating system version. \n            getSystemVersion() - Gets the device OS version.\n                iOS: "11.0"\n                Android: "7.1.1"\n                Windows: ?\n        ',
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CF", "CF"),
                    ("CM", "CM"),
                    ("TF", "TF"),
                    ("TM", "TM"),
                    ("NB", "NB"),
                    ("OT", "OT"),
                    ("DA", "DA"),
                ],
                help_text="Self-identified gender identity of user",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_latino",
            field=models.CharField(
                blank=True,
                choices=[("YE", "YE"), ("NO", "NO"), ("DA", "DA")],
                help_text="Latino or Hispanic origin",
                max_length=2,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="account",
            name="race",
        ),
        migrations.AddField(
            model_name="account",
            name="race",
            field=models.JSONField(
                blank=True,
                choices=[
                    ("NA", "NA"),
                    ("BL", "BL"),
                    ("AS", "AS"),
                    ("PI", "PI"),
                    ("WH", "WH"),
                    ("OT", "OT"),
                    ("DA", "DA"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="sexual_orien",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BS", "BS"),
                    ("SG", "SG"),
                    ("US", "US"),
                    ("HS", "HS"),
                    ("OT", "OT"),
                    ("DA", "DA"),
                ],
                help_text="Self-identified sexual orientation of user",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="zip",
            field=models.CharField(help_text="User's zip code", max_length=25),
        ),
    ]
