from datetime import datetime

from ninja import Field, Schema
from pydantic import ConfigDict
from typing_extensions import Self


class DeviceInSchema(Schema):
    model_config = ConfigDict(extra="forbid")

    device_id: str = Field(
        max_length=250,
        description="""A unique id generated by the app when it is first installed"
            on a device. Used for authentication on subsequent calls.""",
    )
    device_model: str | None = Field(
        default=None,
        max_length=25,
        description="""Unique identifier for the device's model.
            <br><brgetDeviceid() - Gets the device ID.
            <br>iOS: "iPhone7,2"
            <br>Android: "goldfish"
            <br>Windows: "Y3R94UC#AC4"
        """,
    )
    manufacturer: str | None = Field(
        default=None,
        max_length=25,
        description="""Manufacturer of the device.
            <br><br>getManufacturer() - Gets the device manufacturer
            <br>iOS: "Apple"
            <br>Android: "Google"
            <br>Windows: ?
        """,
    )
    os_name: str | None = Field(
        default=None,
        max_length=25,
        description="""Operating system of the device.
            <br><br>getSystemName() - Gets the device OS name.
            <br>iOS: "iOS" on newer iOS devices "iPhone OS" on older devices 
                (including older iPad models), "iPadOS" for iPads using iPadOS 15.0 or higher.
            <br>Android: "Android"
            <br>Windows: ?
        """,
    )
    os_version: str | None = Field(
        default=None,
        max_length=25,
        description="""Device operating system version. 
            <br><br>getSystemVersion() - Gets the device OS version.
            <br>iOS: "11.0"
            <br>Android: "7.1.1"
            <br>Windows: ?
        """,
    )


class DeviceOutSchema(Schema):
    model_config = ConfigDict(extra="forbid")

    device_id: str = Field(
        max_length=250,
        description="""A unique id generated by the app when it is first installed"
            on a device. Used for authentication on subsequent calls.""",
    )
    created: datetime = Field(
        description="When the record was created/device was registered"
    )
    device_model: str | None = Field(
        default=None,
        max_length=25,
        description="""Unique identifier for the device's model.
            <br><br>getDeviceid() - Gets the device ID.
            <br>iOS: "iPhone7,2"
            <br>Android: "goldfish"
            <br>Windows: "Y3R94UC#AC4"
        """,
    )
    manufacturer: str | None = Field(
        default=None,
        max_length=25,
        description="""Manufacturer of the device.
            <br><br>getManufacturer() - Gets the device manufacturer
            <br>iOS: "Apple"
            <br>Android: "Google"
            <br>Windows: ?
        """,
    )
    os_name: str | None = Field(
        default=None,
        max_length=25,
        description="""Operating system of the device.
            <br><br>getSystemName() - Gets the device OS name.
            <br>iOS: "iOS" on newer iOS devices "iPhone OS" on older devices 
                (including older iPad models), "iPadOS" for iPads using iPadOS 15.0 or higher.
            <br>Android: "Android"
            <br>Windows: ?
        """,
    )
    os_version: str | None = Field(
        default=None,
        max_length=25,
        description="""Device operating system version. 
            <br><br>getSystemVersion() - Gets the device OS version.
            <br>iOS: "11.0"
            <br>Android: "7.1.1"
            <br>Windows: ?
        """,
    )


class ErrorSchema(Schema):
    message: str = Field(
        description="Error message to display",
    )
