from ninja import Field, Schema
from pydantic import ConfigDict


class DeviceInSchema(Schema):
    model_config = ConfigDict(extra="forbid")

    device_id: str = Field(
        max_length=250,
        description="""A unique id generated by the app when it is first installed
            on a device. Used for authentication on subsequent calls.""",
    )
    device_model: str | None = Field(
        default=None,
        max_length=25,
        description="""Unique identifier for the device's model.\n
            \ngetDeviceid() - Gets the device ID.\n
            \tiOS: "iPhone7,2"\n
            \tAndroid: "goldfish"\n
            \tWindows: "Y3R94UC#AC4"
        """,
    )
    manufacturer: str | None = Field(
        default=None,
        max_length=25,
        description="""Manufacturer of the device.\n
            \ngetManufacturer() - Gets the device manufacturer\n
            \tiOS: "Apple"\n
            \tAndroid: "Google"\n
            \tWindows: ?
        """,
    )
    os_name: str | None = Field(
        default=None,
        max_length=25,
        description="""Operating system of the device.\n
            \ngetSystemName() - Gets the device OS name.\n
            \tiOS: "iOS" on newer iOS devices "iPhone OS" on older devices\n
            \t(including older iPad models), "iPadOS" for iPads using iPadOS 15.0 or higher.\n
            \tAndroid: "Android"\n
            \tWindows: ?
        """,
    )
    os_version: str | None = Field(
        default=None,
        max_length=25,
        description="""Device operating system version.\n
            \ngetSystemVersion() - Gets the device OS version.\n
            \tiOS: "11.0"\n
            \tndroid: "7.1.1"\n
            \tWindows: ?
        """,
    )


class ErrorSchema(Schema):
    message: str = Field(
        description="Error message to display",
    )
